terminate called after throwing an instance of 'rose_exception'
  what():  abort
terminate called after throwing an instance of 'rose_exception'
  what():  abort
terminate called after throwing an instance of 'rose_exception'
  what():  abort
terminate called after throwing an instance of 'rose_exception'
  what():  abort
terminate called after throwing an instance of 'rose_exception'
  what():  abort
